name: CI

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Unit Tests
        run: npm run test
